version: '3.8'

services:
  back:
    build: ./back
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - rede_1
    volumes:
      - ./back/src:/var/www/html/src
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - rede_1
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: senha123
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  rede_1:
    driver: bridge